### ISSUE TITLE
odd bugs

### ISSUE THREAD

**Issue by KlavsKlavsen** [danielfoehrKn/kubeswitch#5]
```
$ switch --config-directory ~/.kube
Error: unknown flag: --config-path
```

and README says to use --kubeconfig-directory.. but thats not listed in the --help output ?

**Comment by danielfoehrKn** [comment]
Hi, thanks for reporting. The READ.ME was outdated. 

The flag is called `--kubeconfig-path` because it can be either in vault or on the local filesystem.

The name `--config-directory` is misleading, it should be set to the config file not the directory. (default "~/.kube/switch-config.yaml").  I will adjust the naming soon and put that into a new release.

**Comment by danielfoehrKn** [comment]
Please bear in mind that setting the config file via is not required atm. It is only optional to configure the `kubeconfigRediscoveryInterval` for the kubeconfig index, and to configure `hooks`. So the chance is that you do not even need it.

**Comment by danielfoehrKn** [comment]
Closing this for now. Please reopen if it persists.
